Failed to execute code at iteration 4: Traceback (most recent call last):
  File "/home/anyaji/grounded-edit/playground/data/food_slide_6/iter_4/gpt-4o/code.py", line 49, in <module>
    slide.shapes.add_picture(characters_image_path, Inches(8), Inches(5), Inches(2.5), Inches(2.5))
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/shapes/shapetree.py", line 370, in add_picture
    image_part, rId = self.part.get_or_add_image_part(image_file)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/parts/slide.py", line 50, in get_or_add_image_part
    image_part = self._package.get_or_add_image_part(image_file)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/package.py", line 38, in get_or_add_image_part
    return self._image_parts.get_or_add_image_part(image_file)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/package.py", line 153, in get_or_add_image_part
    image = Image.from_file(image_file)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/parts/image.py", line 163, in from_file
    with open(image_file, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../media/characters_with_wine_glasses.jpg'
