Failed to execute code at iteration 3: Traceback (most recent call last):
  File "/home/anyaji/grounded-edit/playground/data/business_slide_3/iter_3/gpt-4o/code.py", line 29, in <module>
    background.paste(img, (0, 0), img)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/PIL/Image.py", line 1847, in paste
    self.im.paste(im, box, mask.im)
ValueError: bad transparency mask
